#pragma once

// author: uniqs
// uniqs@163.com
// ====================== This file is generated by uniqs, don't change it!!!!!! ====================== 



#include "BaseTypes.h"

class DT{{%=SheetName%}}
{
	public:
	DT{{%=SheetName%}}() :
			{{%Loop.col%}}
		{{%=ColInitValue%}}
			{{%LoopEnd.col%}}
	{}
	bool LoadDT(simdjson::ondemand::value& tValue, {{%=row:col.2:1}}& key, std::string& err)
	{
			{{%Loop.col%}}
		if (!{{%=TransColType2ReadFunc.row.3%}}(tValue, "{{%=row.2%}}", {{%=row.2%}})) { err = " DT{{%=SheetName%}}.{{%=row.2%}} error."; return false; }
			{{%LoopEnd.col%}}
		key = {{%=row:col.2:1}};

		return true;
	}

public:
{{%Loop.col%}}
	{{%=ColType%}} {{%=row.2%}};// {{%=row.4%}}
{{%LoopEnd.col%}}
};

extern std::unique_ptr<DTCfgTable<{{%=row:col.2:1}}, DT{{%=SheetName%}}>> g_pCfg_{{%=SheetName%}};// DT{{%=SheetName%}}.json

